### PR TITLE
Add support for Django 4.2

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by johnthagen** [comment]
I'm confused about why PyPy tests are failing? 🤔

**Comment by vinnyrose** [comment]
> I'm confused about why PyPy tests are failing? 🤔

probably https://github.com/django/asgiref/issues/393

**Comment by johnthagen** [comment]
Maybe we could temporarily put a upper bound on `asgiref` during testing?

**Comment by johnthagen** [comment]
@vinnyrose Thanks for tracking down the CI issue!

**Comment by johnthagen** [comment]
@vinnyrose Your changes look good to me. Anything else needed to merged this PR? Thanks.

**Comment by vinnyrose** [comment]
> @vinnyrose Your changes look good to me. Anything else needed to merged this PR? Thanks.

Thanks for the reminder, I meant to get to this in the last few days. Hope to have this in by the weekend.

**Comment by johnthagen** [comment]
image

**Pull request merged**
